A

In [3]:
import numpy as np

# Task a
# Step 1: Create random vector
vector = np.random.randint(1, 21, size=15)
print("Original Vector:\n", vector)

# Step 2: Reshape to 3 by 5
reshaped_vector = vector.reshape(3, 5)
print("Reshaped Array:\n", reshaped_vector)

# Step 3: Print array shape
print("Array Shape:", reshaped_vector.shape)

# Step 4: Replace the max in each row with 0
for row in reshaped_vector:
    row[np.argmax(row)] = 0
print("Modified Array with max replaced by 0:\n", reshaped_vector)

# Create a 2-dimensional array of size 4x3 composed of 4-byte integer elements
array_2d = np.random.randint(1, 100, size=(4, 3), dtype=np.int32)
print("2D Array:\n", array_2d)
print("Shape:", array_2d.shape)
print("Type:", type(array_2d))
print("Data Type:", array_2d.dtype)

Original Vector:
 [ 4  9 16 15 12 14  4 10  9 11 12 16  7 10 11]
Reshaped Array:
 [[ 4  9 16 15 12]
 [14  4 10  9 11]
 [12 16  7 10 11]]
Array Shape: (3, 5)
Modified Array with max replaced by 0:
 [[ 4  9  0 15 12]
 [ 0  4 10  9 11]
 [12  0  7 10 11]]
2D Array:
 [[99 21 96]
 [89 20 19]
 [22 48 15]
 [95 29 97]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data Type: int32


B

In [4]:
array_b = np.array([[3, -2], [1, 0]])
eigenvalues, eigenvectors = np.linalg.eig(array_b)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [2. 1.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


C

In [5]:
array_c = np.array([[0, 1, 2], [3, 4, 5]])
diagonal_sum = np.trace(array_c)
print("Sum of diagonal elements:", diagonal_sum)

Sum of diagonal elements: 4


D

In [6]:
array_d = np.array([[1, 2], [3, 4], [5, 6]])
reshaped_array_d = array_d.reshape(2, 3)
print("Reshaped Array 3x2 to 2x3:\n", reshaped_array_d)

Reshaped Array 3x2 to 2x3:
 [[1 2 3]
 [4 5 6]]
